### ISSUE TITLE
Cannot read property 'src' of undefined/null

### ISSUE THREAD

**Issue by RIP21** [infeng/react-viewer#92] opened 2019-12-19 14:56 UTC
Hi there mate! :)

We're getting these errors all the time, on 3.1.
We're using typescript, which means that we're pretty much sure that we're compliant with the typings.

I can't give you any more clue, it will be nice if that is sorted, or typings are changed accordingly.

I cannot reproduce it much, so I can't help with that at least for now. Sorry.

![image](https://user-images.githubusercontent.com/3940079/71183103-a8ffa400-2277-11ea-8212-059b3e25b0b6.png)
![image](https://user-images.githubusercontent.com/3940079/71183231-e8c68b80-2277-11ea-8cde-69dc5c2e91aa.png)
![image](https://user-images.githubusercontent.com/3940079/71183520-6b4f4b00-2278-11ea-90b2-91597e993ea8.png)

**Comment by KerrGrah** [comment] 2019-12-20 22:06
It seems to me the issue is in `getActiveImage` which has:

```
let realActiveIndex = null;
    if (activeIndex2 !== undefined) {
      realActiveIndex = activeIndex2;
    } else {
      realActiveIndex = state.activeIndex;
    }
    if (images.length > 0 && realActiveIndex >= 0) {
      activeImg2 = images[realActiveIndex];
    }

    return activeImg2
```


`state.activeIndex` is not reset with new `prop.activeIndex` when `visible` is set to true. So old state`activeIndex` is used on new props `images`. 

Hence `activeImg2` is `undefined` and the `src` access on `activeImg` fails at 
```
imgSrc={state.loadFailed ? (props.defaultImg.src || activeImg.src) : activeImg.src}
```

**Comment by KerrGrah** [comment] 2019-12-24 11:26
All errors resolved by passing `key={images.length}` to viewer, causing re-initiation if amount of images changes.

**Comment by infeng** [comment] 2019-12-25 16:53
When open `react-viewer`, you should set correct `activeIndex`

**Closed** 2020-06-23 16:15 UTC
